### ISSUE TITLE
BlueGenes Tool API Tutorial link broken

### ISSUE THREAD

**Issue by MinervaLong** [intermine/gsoc#17]
The link for the tutorial is broken @yochannah . Could you indicate where to find the tutorial? Thank you

**Comment by yochannah** [comment]
Hey @MinervaLong, thanks for flagging this up! The tutorial is here - https://github.com/intermine/bluegenes/blob/dev/docs/tools/tool-api-tutorial.md what page did you find the broken link? (If you feel up to making a PR to fix it, that would be _awesome_!

**Comment by yochannah** [comment]
Great job - thanks for fixing this with #18, @MinervaLong ! <3
