### ISSUE TITLE
GSoC proposal template

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/gsoc#6]
My suggestions:

1. no page limit on the proposal part. (cloud one is going to be LONG) 
2. add a section for risk analysis. Make optional as maybe not appropriate for all?
3. example proposal for students? Nupur and Kostas agreed to let us use theirs

Each of my project specifications has a (broken) link to the proposal. Let me know when this is done and I will update with the good link.

**Comment by yochannah** [comment]
doneded.
